---
  kind: pipeline
  type: docker
  name: develop

  clone:
    disable: true

  platform:
    arch: amd64
    os: linux

  steps:
    - name: clone
      image: alpine/git
      commands:
        - git clone https://github.com/murigama/wordpress-drone-deploy.git .
        - git checkout $DRONE_COMMIT

    - name: build-site
      image: alpine:latest
      depends_on:
        - clone
      #commands:

    - name: publish
      image: plugins/ecr
      depends_on:
        - build-site
      settings:
        access_key:
          from_secret: access_key
        secret_key:
          from_secret: secret_key
        region: us-west-2
        repo: wordpress-drone-deploy
        tags:
          - latest
        registry: 990444934042.dkr.ecr.us-east-2.amazonaws.com
      environment:
        FORCE_NEW_DEPLOYMENT: true

    - name: deploy
      image: gportugues/drone-ecs-deploy
      depends_on:
        - publish
      settings:
        cluster: wordpress-drone-deploy
        service: wordpress-drone-deploy
        image_name: 990444934042.dkr.ecr.us-east-2.amazonaws.com/wordpress-drone-deploy:latest
        aws_region: us-west-2
        timeout: "1200"
        max: "200"
        min: "100"
        aws_access_key_id:
          from_secret: access_key
        aws_secret_access_key:
          from_secret: secret_key
        task_definition: {"taskDefinition":{"requiresCompatibilities": ["FARGATE", "EC2"], "networkMode":"awsvpc"}}

  trigger:
    branch:
    - main
    event:
    - push

